### PR TITLE
changed based on suggestion here

### PR DESCRIPTION
**Pull request by afterbangx**
https://groups.google.com/forum/#!topic/sonarqube/oU4FSb8rKEE

I was having the exact same issue in the post above. I made the suggested changes and authentication started working for me. I see it's been two weeks and he still hasn't sent a PR so I figured I would do it myself. I don't know enough about how it works on other systems to know if it will break for others but all tests are green so I'm assuming it's ok.

### CODE REVIEW

**Comment by julienlancelot** [comment]
Thanks for your contribution, I've created a JIRA ticket to handle it : https://jira.sonarsource.com/browse/LDAP-60

**Comment by MichelZ** [comment]
Same issue here. 
When can we expect this to be included?

**Comment by dee-see** [comment]
Same issue as well. With the Active Directory plugin broken as well, windows users are left hanging with SonarQube 6.2...

**Comment by joshlrogers** [comment]
I would very much like to see this PR pulled in and released.  At this point we are abandoning using LDAP with SonarQube until this issue is resolved.

**Comment by dee-see** [comment]
@julienlancelot I see that this issue is not on the 2.2 road map. Any hopes that it makes the version after that?

**Comment by julienlancelot** [comment]
@dee-see It indeed won't be included in 2.2 version, still no ETA for the moment

**Comment by julienlancelot** [comment]
Auto discovery mode is deprecated and is going to be dropped in futur version, I'm closing this PR

**Pull request closed without merging**
